In [6]:
import cv2
import pafy
#url of the video to predict Age and gender
url = 'https://www.youtube.com/watch?v=c07IsbSNqfI&feature=youtu.be'
vPafy = pafy.new(url)
play = vPafy.getbest(preftype="mp4") 
cap = cv2.VideoCapture(play.url)
cv2.imshow('frame',cap)

TypeError: Expected Ptr<cv::UMat> for argument '%s'

In [ ]:
import cv2
import numpy as np
import pafy
#url of the video to predict Age and gender
url = 'https://www.youtube.com/watch?v=c07IsbSNqfI&feature=youtu.be'
vPafy = pafy.new(url)
play = vPafy.getbest(preftype="mp4") 
cap = cv2.VideoCapture(play.url)
#video_capture = cv2.VideoCapture("girl1.jpg")



cap.set(3, 480) #set width of the frame
cap.set(4, 640) #set height of the frame
MODEL_MEAN_VALUES = (78.4263377603, 87.7689143744, 114.895847746)
age_list = ['(0, 2)', '(4, 6)', '(8, 12)', '(15, 20)', '(25, 32)', '(38, 43)', '(48, 53)', '(60, 100)']
gender_list = [ 'Male', 'Female']
def load_caffe_models():
    gender_net = cv2.dnn.readNetFromCaffe('gender_deploy.prototxt', 'gender_net.caffemodel')

    age_net = cv2.dnn.readNetFromCaffe('age_deploy.prototxt', 'age_net.caffemodel')
    return(age_net, gender_net)
def video_detector(age_net, gender_net):
    font = cv2.FONT_HERSHEY_SIMPLEX
    #faceCascade = cv2.CascadeClassifier(r'C:\Users\USER\Documents\Python Scripts\Drowsiness detection\haar cascade files\haarcascade_frontalface_alt.xml')

    #video_capture = cv2.VideoCapture(0)

    while True:
        faceCascade = cv2.CascadeClassifier(r'C:\Users\USER\Documents\Python Scripts\Drowsiness detection\haar cascade files\haarcascade_frontalface_alt.xml')
        video_capture = cv2.VideoCapture("girl1.jpg")
        #cap = cv2.VideoCapture(play.url)


        ret, image = video_capture.read()

        if ret == True:
            print(ret)
            print(image)

            gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

            faces = faceCascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5)
           
        if(len(faces)>0):
            print("Found {} faces".format(str(len(faces))))
            for (x, y, w, h )in faces:
                cv2.rectangle(image, (x, y), (x+w, y+h), (255, 255, 0), 2)
        #cv2.imshow('frame', image)  

        #Get Face 
                face_img = image[y:y+h, h:h+w].copy()
            blob = cv2.dnn.blobFromImage(face_img, 1, (227, 227), MODEL_MEAN_VALUES, swapRB=False)
        #Predict Gender
            gender_net.setInput(blob)
            gender_preds = gender_net.forward()
            gender = gender_list[gender_preds[0].argmax()]
            print("Gender : " + gender)
        #Predict Age
            age_net.setInput(blob)
            age_preds = age_net.forward()
            age = age_list[age_preds[0].argmax()]
            print("Age Range: " + age)
            overlay_text = "%s %s" % (gender, age)
            cv2.putText(image, overlay_text, (x, y), font, 1, (255, 255, 255), 2, cv2.LINE_AA)
            cv2.imshow('frame', image)  
        #0xFF is a hexadecimal constant which is 11111111 in binary.
            if cv2.waitKey(1) == ord('q'): 
                break
if __name__ == "__main__":
    age_net, gender_net = load_caffe_models()
    video_detector(age_net, gender_net)
    

True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ...
  [ 38  56  55]
  [ 37  56  57]
  [ 37  56  57]]

 ...

 [[ 46  59  61]
  [ 44  57  59]
  [ 41  54  56]
  ...
  [108 129 144]
  [110 131 146]
  [111 132 147]]

 [[ 47  60  62]
  [ 45  58  60]
  [ 42  55  57]
  ...
  [112 133 148]
  [114 135 150]
  [116 137 152]]

 [[ 48  61  63]
  [ 46  59  61]
  [ 44  57  59]
  ...
  [114 135 150]
  [117 138 153]
  [119 140 155]]]
Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ...
  [ 38  56  55]
  [ 37  56  57]
  [ 37  56  57]]

Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ...
  [ 38  56  55]
  [ 37  56  57]
  [ 37  56  57]]

 ...

 [[ 46  59  61]
  [ 44  57  59]
  [ 41  54  56]
  ...
  [108 129 144]
  [110 131 146]
  [111 132 147]]

 [[ 47  60  62]
  [ 45  58  60]
  [ 42  55  57]
  ...
  [112 133 148]
  [114 135 150]
  [116 137 152]]

 [[ 48  61  63]
  [ 46  59  61]
  [ 44  57  59]
  ...
  [114 135 150]
  [117 138 153]
  [119 140 155]]]
Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ..

Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ...
  [ 38  56  55]
  [ 37  56  57]
  [ 37  56  57]]

 ...

 [[ 46  59  61]
  [ 44  57  59]
  [ 41  54  56]
  ...
  [108 129 144]
  [110 131 146]
  [111 132 147]]

 [[ 47  60  62]
  [ 45  58  60]
  [ 42  55  57]
  ...
  [112 133 148]
  [114 135 150]
  [116 137 152]]

 [[ 48  61  63]
  [ 46  59  61]
  [ 44  57  59]
  ...
  [114 135 150]
  [117 138 153]
  [119 140 155]]]
Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ..

Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ...
  [ 38  56  55]
  [ 37  56  57]
  [ 37  56  57]]

 ...

 [[ 46  59  61]
  [ 44  57  59]
  [ 41  54  56]
  ...
  [108 129 144]
  [110 131 146]
  [111 132 147]]

 [[ 47  60  62]
  [ 45  58  60]
  [ 42  55  57]
  ...
  [112 133 148]
  [114 135 150]
  [116 137 152]]

 [[ 48  61  63]
  [ 46  59  61]
  [ 44  57  59]
  ...
  [114 135 150]
  [117 138 153]
  [119 140 155]]]
Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ..

Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ...
  [ 38  56  55]
  [ 37  56  57]
  [ 37  56  57]]

 ...

 [[ 46  59  61]
  [ 44  57  59]
  [ 41  54  56]
  ...
  [108 129 144]
  [110 131 146]
  [111 132 147]]

 [[ 47  60  62]
  [ 45  58  60]
  [ 42  55  57]
  ...
  [112 133 148]
  [114 135 150]
  [116 137 152]]

 [[ 48  61  63]
  [ 46  59  61]
  [ 44  57  59]
  ...
  [114 135 150]
  [117 138 153]
  [119 140 155]]]
Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ..

Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ...
  [ 38  56  55]
  [ 37  56  57]
  [ 37  56  57]]

 ...

 [[ 46  59  61]
  [ 44  57  59]
  [ 41  54  56]
  ...
  [108 129 144]
  [110 131 146]
  [111 132 147]]

 [[ 47  60  62]
  [ 45  58  60]
  [ 42  55  57]
  ...
  [112 133 148]
  [114 135 150]
  [116 137 152]]

 [[ 48  61  63]
  [ 46  59  61]
  [ 44  57  59]
  ...
  [114 135 150]
  [117 138 153]
  [119 140 155]]]
Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ..

Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ...
  [ 38  56  55]
  [ 37  56  57]
  [ 37  56  57]]

 ...

 [[ 46  59  61]
  [ 44  57  59]
  [ 41  54  56]
  ...
  [108 129 144]
  [110 131 146]
  [111 132 147]]

 [[ 47  60  62]
  [ 45  58  60]
  [ 42  55  57]
  ...
  [112 133 148]
  [114 135 150]
  [116 137 152]]

 [[ 48  61  63]
  [ 46  59  61]
  [ 44  57  59]
  ...
  [114 135 150]
  [117 138 153]
  [119 140 155]]]
Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ..

Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ...
  [ 38  56  55]
  [ 37  56  57]
  [ 37  56  57]]

 ...

 [[ 46  59  61]
  [ 44  57  59]
  [ 41  54  56]
  ...
  [108 129 144]
  [110 131 146]
  [111 132 147]]

 [[ 47  60  62]
  [ 45  58  60]
  [ 42  55  57]
  ...
  [112 133 148]
  [114 135 150]
  [116 137 152]]

 [[ 48  61  63]
  [ 46  59  61]
  [ 44  57  59]
  ...
  [114 135 150]
  [117 138 153]
  [119 140 155]]]
Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ..

Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ...
  [ 38  56  55]
  [ 37  56  57]
  [ 37  56  57]]

 ...

 [[ 46  59  61]
  [ 44  57  59]
  [ 41  54  56]
  ...
  [108 129 144]
  [110 131 146]
  [111 132 147]]

 [[ 47  60  62]
  [ 45  58  60]
  [ 42  55  57]
  ...
  [112 133 148]
  [114 135 150]
  [116 137 152]]

 [[ 48  61  63]
  [ 46  59  61]
  [ 44  57  59]
  ...
  [114 135 150]
  [117 138 153]
  [119 140 155]]]
Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ..

Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ...
  [ 38  56  55]
  [ 37  56  57]
  [ 37  56  57]]

 ...

 [[ 46  59  61]
  [ 44  57  59]
  [ 41  54  56]
  ...
  [108 129 144]
  [110 131 146]
  [111 132 147]]

 [[ 47  60  62]
  [ 45  58  60]
  [ 42  55  57]
  ...
  [112 133 148]
  [114 135 150]
  [116 137 152]]

 [[ 48  61  63]
  [ 46  59  61]
  [ 44  57  59]
  ...
  [114 135 150]
  [117 138 153]
  [119 140 155]]]
Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ..

Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ...
  [ 38  56  55]
  [ 37  56  57]
  [ 37  56  57]]

 ...

 [[ 46  59  61]
  [ 44  57  59]
  [ 41  54  56]
  ...
  [108 129 144]
  [110 131 146]
  [111 132 147]]

 [[ 47  60  62]
  [ 45  58  60]
  [ 42  55  57]
  ...
  [112 133 148]
  [114 135 150]
  [116 137 152]]

 [[ 48  61  63]
  [ 46  59  61]
  [ 44  57  59]
  ...
  [114 135 150]
  [117 138 153]
  [119 140 155]]]
Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ..

Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ...
  [ 38  56  55]
  [ 37  56  57]
  [ 37  56  57]]

 ...

 [[ 46  59  61]
  [ 44  57  59]
  [ 41  54  56]
  ...
  [108 129 144]
  [110 131 146]
  [111 132 147]]

 [[ 47  60  62]
  [ 45  58  60]
  [ 42  55  57]
  ...
  [112 133 148]
  [114 135 150]
  [116 137 152]]

 [[ 48  61  63]
  [ 46  59  61]
  [ 44  57  59]
  ...
  [114 135 150]
  [117 138 153]
  [119 140 155]]]
Found 1 faces
Gender : Female
Age Range: (25, 32)
True
[[[ 47  76  78]
  [ 47  76  78]
  [ 45  76  78]
  ...
  [ 37  55  54]
  [ 36  55  56]
  [ 37  56  57]]

 [[ 46  75  77]
  [ 47  76  78]
  [ 46  77  79]
  ...
  [ 39  57  56]
  [ 38  57  58]
  [ 38  57  58]]

 [[ 47  76  78]
  [ 48  77  79]
  [ 47  78  80]
  ..

In [1]:
import cv2

In [2]:
faceCascade = cv2.CascadeClassifier(r'C:\Users\USER\Documents\Python Scripts\Drowsiness detection\haarcascade_frontalface_alt.xml')
faceCascade

<CascadeClassifier 0000000007E049F0>

In [1]:
import cv2
faceCascade = cv2.CascadeClassifier(r'C:\Users\USER\Documents\Python Scripts\Drowsiness detection\haar cascade files\haarcascade_frontalface_alt.xml')

video_capture = cv2.VideoCapture(0)

while True:

    ret, frame = video_capture.read()

    if ret == True:
        print(ret)
        print(frame)

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        faces = faceCascade.detectMultiScale(frame, scaleFactor=1.1, minNeighbors=5)
           
        # Draw a rectangle around the faces
        for (x, y, w, h) in faces:
            cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

        # Display the resulting frame
        cv2.imshow('Video', frame)

        if cv2.waitKey(1)==ord('e'):
            break


True
[[[211 225 222]
  [211 225 222]
  [209 225 223]
  ...
  [178 203 203]
  [182 203 206]
  [182 203 206]]

 [[211 225 222]
  [211 225 222]
  [209 225 223]
  ...
  [179 203 205]
  [179 203 205]
  [180 204 206]]

 [[209 225 222]
  [209 225 222]
  [209 225 223]
  ...
  [179 203 205]
  [176 203 209]
  [177 204 210]]

 ...

 [[ 54 101 122]
  [ 54 101 122]
  [ 54  99 119]
  ...
  [ 83 114 115]
  [ 80 111 119]
  [ 80 111 119]]

 [[ 54 103 124]
  [ 52 101 122]
  [ 52 101 117]
  ...
  [ 86 119 120]
  [ 78 112 111]
  [ 78 112 111]]

 [[ 54 104 123]
  [ 52 102 121]
  [ 52 101 117]
  ...
  [ 88 123 119]
  [ 78 112 111]
  [ 75 109 108]]]
True
[[[158 191 186]
  [158 191 186]
  [159 190 185]
  ...
  [119 157 152]
  [116 156 151]
  [113 153 148]]

 [[160 191 186]
  [159 190 185]
  [161 189 186]
  ...
  [123 155 154]
  [116 153 151]
  [114 151 149]]

 [[162 190 187]
  [161 189 186]
  [161 189 186]
  ...
  [119 150 151]
  [113 147 146]
  [112 146 145]]

 ...

 [[ 12  34  48]
  [ 12  34  48]
  [ 16  38

True
[[[ 47  72 104]
  [ 45  70 102]
  [ 41  66  98]
  ...
  [ 44  62  81]
  [ 49  67  88]
  [ 49  67  88]]

 [[ 51  71 106]
  [ 49  69 104]
  [ 43  68 100]
  ...
  [ 50  61  81]
  [ 46  64  85]
  [ 49  67  88]]

 [[ 51  71 106]
  [ 49  69 104]
  [ 47  67 102]
  ...
  [ 48  62  80]
  [ 50  64  82]
  [ 53  67  85]]

 ...

 [[  7  24  34]
  [  7  24  34]
  [  7  25  38]
  ...
  [100 150 182]
  [ 99 147 184]
  [ 99 147 184]]

 [[  7  23  36]
  [  7  23  36]
  [  9  25  38]
  ...
  [ 98 149 179]
  [ 99 150 178]
  [ 99 150 178]]

 [[  5  23  36]
  [  5  23  36]
  [  5  23  36]
  ...
  [ 98 149 179]
  [ 98 149 179]
  [ 99 150 180]]]
True
[[[ 40  62  90]
  [ 43  65  93]
  [ 48  65  94]
  ...
  [ 69  68  84]
  [ 71  73  88]
  [ 73  75  90]]

 [[ 36  59  89]
  [ 38  61  91]
  [ 39  65  94]
  ...
  [ 66  68  83]
  [ 69  71  86]
  [ 71  73  88]]

 [[ 37  59  87]
  [ 38  60  88]
  [ 41  65  93]
  ...
  [ 58  66  74]
  [ 66  70  78]
  [ 67  71  79]]

 ...

 [[  9  21  39]
  [ 11  23  41]
  [ 12  25

True
[[[ 21  52  60]
  [ 27  58  66]
  [ 34  63  64]
  ...
  [151 171 190]
  [153 171 192]
  [152 170 191]]

 [[ 19  53  65]
  [ 23  57  69]
  [ 30  59  67]
  ...
  [151 171 190]
  [153 171 192]
  [153 171 192]]

 [[ 31  56  69]
  [ 29  54  67]
  [ 33  56  68]
  ...
  [147 172 190]
  [151 171 190]
  [149 169 188]]

 ...

 [[  0  21  35]
  [  0  22  36]
  [  8  24  37]
  ...
  [100 140 174]
  [ 81 125 156]
  [ 60 104 135]]

 [[  5  29  38]
  [  5  29  38]
  [  9  27  40]
  ...
  [111 147 181]
  [ 82 124 165]
  [ 45  87 128]]

 [[  7  29  43]
  [  5  27  41]
  [  7  30  42]
  ...
  [105 145 179]
  [ 84 127 160]
  [ 47  90 123]]]
True
[[[ 26  57  85]
  [ 26  57  85]
  [ 24  52  81]
  ...
  [148 177 178]
  [150 180 179]
  [152 182 181]]

 [[ 22  55  83]
  [ 22  55  83]
  [ 20  52  83]
  ...
  [148 176 180]
  [148 179 180]
  [150 181 182]]

 [[ 20  55  78]
  [ 20  55  78]
  [ 20  53  81]
  ...
  [147 175 179]
  [144 177 178]
  [145 178 179]]

 ...

 [[  9  25  24]
  [  6  22  21]
  [  0  19

True
[[[113 147 159]
  [112 146 158]
  [111 148 159]
  ...
  [104 135 136]
  [107 137 141]
  [107 137 141]]

 [[111 146 162]
  [111 146 162]
  [111 146 162]
  ...
  [105 134 135]
  [106 135 136]
  [106 135 136]]

 [[111 149 158]
  [112 150 159]
  [114 152 161]
  ...
  [ 96 128 132]
  [101 134 135]
  [101 134 135]]

 ...

 [[ 66  91 109]
  [ 66  91 109]
  [ 60  92 109]
  ...
  [175 181 156]
  [175 178 149]
  [171 174 145]]

 [[ 67  92 112]
  [ 67  92 112]
  [ 60  92 111]
  ...
  [177 181 156]
  [179 181 149]
  [173 175 143]]

 [[ 63  95 114]
  [ 63  95 114]
  [ 59  94 110]
  ...
  [173 181 156]
  [173 179 149]
  [168 174 144]]]
True
[[[115 142 160]
  [115 142 160]
  [111 145 157]
  ...
  [ 83 101 120]
  [ 86 105 122]
  [ 89 108 125]]

 [[112 144 161]
  [111 143 160]
  [109 141 158]
  ...
  [ 83 103 122]
  [ 86 106 127]
  [ 87 107 128]]

 [[110 147 158]
  [110 147 158]
  [107 145 154]
  ...
  [ 85 103 122]
  [ 86 104 123]
  [ 88 106 125]]

 ...

 [[ 64  99 122]
  [ 60  95 118]
  [ 57  94

True
[[[ 41  51  76]
  [ 39  49  74]
  [ 37  50  72]
  ...
  [147 166 169]
  [147 167 168]
  [146 166 167]]

 [[ 38  52  77]
  [ 37  51  76]
  [ 31  50  74]
  ...
  [144 165 168]
  [146 166 167]
  [147 167 168]]

 [[ 38  54  80]
  [ 36  52  78]
  [ 37  51  76]
  ...
  [144 163 171]
  [142 166 168]
  [142 166 168]]

 ...

 [[ 62 107 127]
  [ 65 110 130]
  [ 68 114 129]
  ...
  [143 169 166]
  [136 163 176]
  [134 161 174]]

 [[ 65 110 130]
  [ 68 113 133]
  [ 70 113 133]
  ...
  [146 167 164]
  [137 164 164]
  [135 162 162]]

 [[ 68 113 133]
  [ 68 113 133]
  [ 68 114 131]
  ...
  [148 167 163]
  [137 164 164]
  [133 160 160]]]
True
[[[ 60  64  97]
  [ 59  63  96]
  [ 58  62  95]
  ...
  [178 206 210]
  [180 209 210]
  [180 209 210]]

 [[ 57  64  96]
  [ 57  64  96]
  [ 53  60  92]
  ...
  [178 206 210]
  [178 207 208]
  [180 209 210]]

 [[ 57  61  89]
  [ 57  61  89]
  [ 55  59  87]
  ...
  [179 206 206]
  [180 208 205]
  [180 208 205]]

 ...

 [[ 78 113 141]
  [ 78 113 141]
  [ 79 116

True
[[[ 45  58  85]
  [ 47  60  87]
  [ 46  67  92]
  ...
  [189 208 216]
  [185 209 216]
  [185 209 216]]

 [[ 37  61  84]
  [ 37  61  84]
  [ 43  65  88]
  ...
  [188 207 217]
  [188 207 217]
  [189 208 218]]

 [[ 45  58  85]
  [ 45  58  85]
  [ 45  58  85]
  ...
  [190 207 215]
  [190 207 215]
  [190 207 215]]

 ...

 [[ 96 123 143]
  [ 95 122 142]
  [ 95 122 142]
  ...
  [149 157 122]
  [147 153 123]
  [144 150 120]]

 [[105 125 144]
  [102 122 141]
  [ 98 123 141]
  ...
  [152 157 123]
  [144 150 113]
  [141 147 110]]

 [[101 126 144]
  [101 126 144]
  [ 96 125 138]
  ...
  [151 160 122]
  [144 150 113]
  [136 142 105]]]
True
[[[ 54  78 114]
  [ 55  79 115]
  [ 63  82 112]
  ...
  [184 211 211]
  [182 213 209]
  [182 213 209]]

 [[ 55  79 115]
  [ 57  81 117]
  [ 57  81 117]
  ...
  [184 212 209]
  [182 213 209]
  [182 213 209]]

 [[ 55  79 115]
  [ 57  81 117]
  [ 63  81 114]
  ...
  [185 212 212]
  [183 213 212]
  [182 212 211]]

 ...

 [[ 86 119 142]
  [ 86 119 142]
  [ 84 119

True
[[[201 221 222]
  [201 221 222]
  [199 223 225]
  ...
  [187 206 203]
  [189 205 202]
  [190 206 203]]

 [[201 221 222]
  [203 223 224]
  [199 224 224]
  ...
  [190 206 204]
  [190 206 204]
  [190 206 204]]

 [[197 221 223]
  [197 221 223]
  [201 222 225]
  ...
  [189 205 203]
  [190 206 204]
  [190 206 204]]

 ...

 [[ 84 120 141]
  [ 84 120 141]
  [ 84 120 141]
  ...
  [137 164 164]
  [143 164 160]
  [144 165 161]]

 [[ 86 121 139]
  [ 86 121 139]
  [ 81 118 136]
  ...
  [140 164 166]
  [139 164 164]
  [137 162 162]]

 [[ 84 121 139]
  [ 81 118 136]
  [ 79 118 136]
  ...
  [138 164 166]
  [135 162 162]
  [134 161 161]]]
True
[[[194 220 217]
  [195 221 218]
  [197 223 220]
  ...
  [186 206 207]
  [188 206 207]
  [190 208 209]]

 [[195 221 218]
  [195 221 218]
  [196 222 219]
  ...
  [185 205 206]
  [188 206 207]
  [188 206 207]]

 [[195 220 220]
  [195 220 220]
  [196 221 221]
  ...
  [187 205 206]
  [189 204 206]
  [189 204 206]]

 ...

 [[ 80 113 141]
  [ 81 114 142]
  [ 88 118

True
[[[137 167 171]
  [137 167 171]
  [139 167 171]
  ...
  [162 189 195]
  [168 192 199]
  [169 193 200]]

 [[133 167 172]
  [133 167 172]
  [137 170 171]
  ...
  [162 189 195]
  [170 194 196]
  [171 195 197]]

 [[135 167 171]
  [137 169 173]
  [137 169 173]
  ...
  [163 187 194]
  [167 191 193]
  [171 195 197]]

 ...

 [[ 88 115 133]
  [ 86 113 131]
  [ 84 111 129]
  ...
  [144 155 154]
  [141 148 160]
  [141 148 160]]

 [[ 86 113 131]
  [ 86 113 131]
  [ 81 113 130]
  ...
  [145 154 152]
  [134 150 149]
  [132 148 147]]

 [[ 86 113 131]
  [ 86 113 131]
  [ 81 113 130]
  ...
  [143 153 148]
  [134 148 146]
  [133 147 145]]]
True
[[[ 64  99 115]
  [ 64  99 115]
  [ 68  97 110]
  ...
  [174 195 198]
  [174 195 198]
  [173 194 197]]

 [[ 64  99 117]
  [ 62  97 115]
  [ 70  95 113]
  ...
  [173 197 199]
  [172 196 198]
  [172 196 198]]

 [[ 63  98 108]
  [ 63  98 108]
  [ 69  97 108]
  ...
  [169 196 204]
  [169 196 204]
  [169 196 204]]

 ...

 [[ 77 117 126]
  [ 77 117 126]
  [ 79 117

True
[[[ 43  52  51]
  [ 45  54  53]
  [ 59  66  65]
  ...
  [185 203 204]
  [185 204 201]
  [185 204 201]]

 [[ 43  52  52]
  [ 45  54  54]
  [ 54  63  63]
  ...
  [184 204 205]
  [184 205 203]
  [183 204 202]]

 [[ 43  52  52]
  [ 45  54  54]
  [ 51  58  58]
  ...
  [184 204 205]
  [184 205 203]
  [184 205 203]]

 ...

 [[ 91 116 136]
  [ 91 116 136]
  [ 90 115 135]
  ...
  [114 137 149]
  [125 139 157]
  [127 141 159]]

 [[ 95 115 134]
  [ 94 114 133]
  [ 87 114 127]
  ...
  [112 131 141]
  [118 135 143]
  [122 139 147]]

 [[ 91 116 136]
  [ 90 115 135]
  [ 85 112 130]
  ...
  [116 135 143]
  [116 134 147]
  [120 138 151]]]
True
[[[ 46  54  70]
  [ 46  54  70]
  [ 46  54  70]
  ...
  [187 202 204]
  [187 202 204]
  [187 202 204]]

 [[ 42  54  72]
  [ 42  54  72]
  [ 48  52  72]
  ...
  [187 202 204]
  [187 202 204]
  [187 202 204]]

 [[ 48  54  69]
  [ 48  54  69]
  [ 50  53  70]
  ...
  [186 201 203]
  [186 201 203]
  [186 201 203]]

 ...

 [[ 82 116 128]
  [ 82 116 128]
  [ 80 117

True
[[[ 47  69  92]
  [ 47  69  92]
  [ 52  66  91]
  ...
  [172 196 198]
  [169 195 197]
  [169 195 197]]

 [[ 43  69  92]
  [ 42  68  91]
  [ 46  69  89]
  ...
  [168 195 201]
  [169 195 197]
  [169 195 197]]

 [[ 41  66  84]
  [ 41  66  84]
  [ 45  65  84]
  ...
  [170 194 201]
  [169 193 200]
  [169 193 200]]

 ...

 [[ 73 120 121]
  [ 74 121 122]
  [ 75 123 126]
  ...
  [147 167 168]
  [133 158 176]
  [117 142 160]]

 [[ 71 121 119]
  [ 72 122 120]
  [ 72 123 124]
  ...
  [144 165 168]
  [126 151 169]
  [119 144 162]]

 [[ 73 120 121]
  [ 74 121 122]
  [ 72 122 125]
  ...
  [144 165 162]
  [128 155 163]
  [117 144 152]]]
True
[[[ 48  68  87]
  [ 49  69  88]
  [ 55  69  87]
  ...
  [165 193 204]
  [166 194 205]
  [167 195 206]]

 [[ 46  69  89]
  [ 47  70  90]
  [ 51  69  88]
  ...
  [165 193 204]
  [166 195 203]
  [166 195 203]]

 [[ 45  65  86]
  [ 48  68  89]
  [ 48  68  87]
  ...
  [166 194 205]
  [166 195 203]
  [167 196 204]]

 ...

 [[ 78 119 130]
  [ 79 120 131]
  [ 82 123

True
[[[ 48  76  80]
  [ 46  74  78]
  [ 48  72  79]
  ...
  [176 202 204]
  [179 204 204]
  [179 204 204]]

 [[ 47  75  79]
  [ 47  75  79]
  [ 47  74  80]
  ...
  [173 202 203]
  [176 203 203]
  [177 204 204]]

 [[ 49  73  82]
  [ 49  73  82]
  [ 50  73  85]
  ...
  [175 202 202]
  [177 203 200]
  [177 203 200]]

 ...

 [[ 86 119 142]
  [ 86 119 142]
  [ 86 119 142]
  ...
  [167 167 140]
  [170 171 147]
  [171 172 148]]

 [[ 79 116 139]
  [ 79 116 139]
  [ 81 116 139]
  ...
  [169 169 142]
  [168 170 143]
  [170 172 145]]

 [[ 80 115 138]
  [ 80 115 138]
  [ 80 115 138]
  ...
  [170 170 143]
  [168 171 142]
  [170 173 144]]]
True
[[[ 27  52  70]
  [ 25  50  68]
  [ 29  48  65]
  ...
  [184 205 208]
  [184 205 208]
  [184 205 208]]

 [[ 31  51  70]
  [ 31  51  70]
  [ 29  49  68]
  ...
  [184 205 208]
  [186 205 213]
  [186 205 213]]

 [[ 39  55  68]
  [ 37  53  66]
  [ 35  51  64]
  ...
  [184 205 208]
  [186 205 213]
  [188 207 215]]

 ...

 [[ 95 122 140]
  [ 95 122 140]
  [ 91 125

True
[[[ 78  93 103]
  [ 81  96 106]
  [ 86 101 111]
  ...
  [193 209 222]
  [197 209 220]
  [196 208 219]]

 [[ 79  96 106]
  [ 82  99 109]
  [ 84 103 106]
  ...
  [192 208 221]
  [194 209 219]
  [194 209 219]]

 [[ 84 101 111]
  [ 86 103 113]
  [ 84 103 113]
  ...
  [191 208 218]
  [191 208 216]
  [191 208 216]]

 ...

 [[ 82 129 155]
  [ 85 132 158]
  [ 87 134 155]
  ...
  [155 162 134]
  [158 165 132]
  [162 169 136]]

 [[ 78 130 155]
  [ 78 130 155]
  [ 87 134 155]
  ...
  [153 160 132]
  [154 163 135]
  [158 167 139]]

 [[ 77 129 154]
  [ 78 130 155]
  [ 87 134 155]
  ...
  [153 160 132]
  [154 163 135]
  [157 166 138]]]
True
[[[197 223 220]
  [197 223 220]
  [197 223 220]
  ...
  [183 211 215]
  [183 212 213]
  [183 212 213]]

 [[197 223 220]
  [197 223 220]
  [197 223 220]
  ...
  [184 208 215]
  [184 210 212]
  [185 211 213]]

 [[197 223 220]
  [197 223 220]
  [197 223 220]
  ...
  [184 211 211]
  [186 211 211]
  [186 211 211]]

 ...

 [[ 92 137 136]
  [ 91 136 135]
  [ 90 136

True
[[[196 233 231]
  [196 233 231]
  [197 229 228]
  ...
  [185 202 210]
  [185 202 210]
  [186 203 211]]

 [[198 232 231]
  [198 232 231]
  [198 230 229]
  ...
  [185 202 210]
  [185 202 210]
  [185 202 210]]

 [[198 232 231]
  [198 232 231]
  [200 232 231]
  ...
  [185 204 207]
  [185 204 207]
  [185 204 207]]

 ...

 [[ 76 123 144]
  [ 77 124 145]
  [ 81 129 148]
  ...
  [152 159 171]
  [152 158 173]
  [154 160 175]]

 [[ 77 122 148]
  [ 77 122 148]
  [ 81 129 148]
  ...
  [150 162 173]
  [150 162 173]
  [151 163 174]]

 [[ 76 123 144]
  [ 77 124 145]
  [ 81 130 146]
  ...
  [148 163 173]
  [154 161 173]
  [155 162 174]]]
True
[[[200 231 232]
  [200 231 232]
  [200 231 232]
  ...
  [181 205 207]
  [181 205 207]
  [181 205 207]]

 [[202 231 232]
  [202 231 232]
  [200 231 232]
  ...
  [181 205 207]
  [179 205 207]
  [179 205 207]]

 [[204 230 232]
  [204 230 232]
  [202 232 231]
  ...
  [181 205 207]
  [179 205 207]
  [179 205 207]]

 ...

 [[102 127 145]
  [104 129 147]
  [101 128

True
[[[204 231 231]
  [204 231 231]
  [204 231 231]
  ...
  [177 204 210]
  [177 205 209]
  [177 205 209]]

 [[202 232 231]
  [202 232 231]
  [202 233 229]
  ...
  [177 204 210]
  [177 204 210]
  [177 204 210]]

 [[200 233 229]
  [200 233 229]
  [202 233 229]
  ...
  [177 204 210]
  [175 204 212]
  [174 203 211]]

 ...

 [[ 86 130 147]
  [ 86 130 147]
  [ 84 130 145]
  ...
  [144 142 122]
  [147 141 120]
  [144 138 117]]

 [[ 89 128 146]
  [ 90 129 147]
  [ 86 130 145]
  ...
  [141 137 117]
  [144 137 118]
  [147 140 121]]

 [[ 85 129 144]
  [ 86 130 145]
  [ 84 130 145]
  ...
  [137 135 115]
  [141 137 117]
  [142 138 118]]]
True
[[[212 231 229]
  [212 231 229]
  [212 231 229]
  ...
  [183 204 207]
  [181 206 206]
  [181 206 206]]

 [[212 231 229]
  [212 231 229]
  [210 231 229]
  ...
  [181 205 207]
  [181 206 206]
  [181 206 206]]

 [[210 231 229]
  [210 231 229]
  [210 231 229]
  ...
  [181 205 207]
  [179 206 206]
  [179 206 206]]

 ...

 [[ 90 123 146]
  [ 88 121 144]
  [ 84 122

True
[[[210 231 227]
  [210 231 227]
  [210 231 227]
  ...
  [193 203 206]
  [193 203 206]
  [193 203 206]]

 [[206 232 228]
  [206 232 228]
  [210 231 227]
  ...
  [189 203 207]
  [193 202 207]
  [193 202 207]]

 [[206 232 229]
  [206 232 229]
  [206 232 228]
  ...
  [187 204 207]
  [189 204 206]
  [189 204 206]]

 ...

 [[ 88 123 141]
  [ 88 123 141]
  [ 88 123 139]
  ...
  [ 94 117 142]
  [ 96 115 145]
  [ 96 115 145]]

 [[ 90 121 143]
  [ 90 121 143]
  [ 90 122 141]
  ...
  [ 96 117 142]
  [ 94 117 142]
  [ 94 117 142]]

 [[ 89 124 142]
  [ 89 124 142]
  [ 89 124 140]
  ...
  [ 94 118 141]
  [ 92 117 142]
  [ 92 117 142]]]
True
[[[202 230 227]
  [204 232 229]
  [204 232 228]
  ...
  [175 204 212]
  [175 205 209]
  [175 205 209]]

 [[202 233 228]
  [202 233 228]
  [204 232 228]
  ...
  [173 204 212]
  [175 205 209]
  [175 205 209]]

 [[204 232 229]
  [204 232 229]
  [204 232 229]
  ...
  [175 204 212]
  [175 205 209]
  [175 205 209]]

 ...

 [[102 126 149]
  [ 98 122 145]
  [ 90 120

True
[[[204 228 235]
  [204 228 235]
  [204 228 237]
  ...
  [183 202 210]
  [183 202 210]
  [184 203 211]]

 [[204 228 235]
  [204 228 235]
  [204 228 235]
  ...
  [179 203 210]
  [183 202 210]
  [183 202 210]]

 [[206 230 232]
  [206 230 232]
  [204 228 235]
  ...
  [181 205 207]
  [181 205 207]
  [181 205 207]]

 ...

 [[ 78 125 133]
  [ 78 125 133]
  [ 76 125 139]
  ...
  [100 124 133]
  [ 96 121 134]
  [ 96 121 134]]

 [[ 77 123 128]
  [ 80 126 131]
  [ 79 127 137]
  ...
  [105 124 134]
  [100 124 133]
  [100 124 133]]

 [[ 76 122 127]
  [ 77 123 128]
  [ 82 129 137]
  ...
  [100 124 131]
  [ 98 124 135]
  [ 98 124 135]]]
True
[[[207 232 232]
  [207 232 232]
  [206 232 229]
  ...
  [177 205 209]
  [177 204 210]
  [177 204 210]]

 [[207 232 232]
  [206 231 231]
  [206 232 229]
  ...
  [177 204 210]
  [177 206 207]
  [176 205 206]]

 [[210 231 228]
  [210 231 228]
  [206 232 228]
  ...
  [175 206 207]
  [175 206 207]
  [175 206 207]]

 ...

 [[ 87 126 137]
  [ 87 126 137]
  [ 85 124

True
[[[202 232 231]
  [202 232 231]
  [202 232 231]
  ...
  [177 204 210]
  [182 210 214]
  [182 210 214]]

 [[202 232 231]
  [202 232 231]
  [202 232 231]
  ...
  [177 204 210]
  [180 207 213]
  [182 209 215]]

 [[202 233 229]
  [202 233 229]
  [202 233 229]
  ...
  [181 207 204]
  [184 209 209]
  [186 211 211]]

 ...

 [[ 99 134 152]
  [ 99 134 152]
  [ 99 134 152]
  ...
  [106 125 128]
  [108 127 125]
  [108 127 125]]

 [[102 134 153]
  [102 134 153]
  [102 134 153]
  ...
  [110 124 123]
  [112 123 122]
  [114 125 124]]

 [[104 136 155]
  [104 136 155]
  [100 135 153]
  ...
  [106 124 125]
  [108 124 123]
  [108 124 123]]]
True
[[[210 229 226]
  [210 229 226]
  [210 231 228]
  ...
  [187 204 207]
  [187 204 207]
  [187 204 207]]

 [[208 229 226]
  [210 231 228]
  [210 231 228]
  ...
  [187 202 210]
  [187 204 207]
  [187 204 207]]

 [[212 231 227]
  [212 231 227]
  [210 231 228]
  ...
  [187 205 206]
  [189 204 206]
  [189 204 206]]

 ...

 [[ 99 130 158]
  [ 96 127 155]
  [ 96 129

True
[[[210 230 231]
  [210 230 231]
  [208 229 232]
  ...
  [173 204 212]
  [169 205 212]
  [169 205 212]]

 [[206 231 231]
  [206 231 231]
  [206 230 232]
  ...
  [173 204 212]
  [173 204 212]
  [173 204 212]]

 [[204 231 231]
  [204 231 231]
  [206 230 232]
  ...
  [178 205 213]
  [177 204 212]
  [177 204 212]]

 ...

 [[ 96 135 151]
  [ 95 134 150]
  [ 95 134 150]
  ...
  [161 166 145]
  [153 158 137]
  [149 154 133]]

 [[ 88 132 147]
  [ 91 135 150]
  [ 88 132 147]
  ...
  [158 165 144]
  [147 155 130]
  [146 154 129]]

 [[ 88 132 147]
  [ 88 132 147]
  [ 87 131 146]
  ...
  [154 162 139]
  [146 154 131]
  [145 153 130]]]
True
[[[150 177 177]
  [150 177 177]
  [152 177 177]
  ...
  [158 181 193]
  [157 182 195]
  [157 182 195]]

 [[149 178 179]
  [148 177 178]
  [150 177 177]
  ...
  [156 182 193]
  [157 182 195]
  [157 182 195]]

 [[150 180 179]
  [149 179 178]
  [149 179 178]
  ...
  [159 183 192]
  [161 184 196]
  [159 182 194]]

 ...

 [[103 138 141]
  [103 138 141]
  [104 139

True
[[[ 43  53  62]
  [ 46  56  65]
  [ 54  58  66]
  ...
  [  7  10  22]
  [  9  12  24]
  [ 11  14  26]]

 [[ 47  54  66]
  [ 48  55  67]
  [ 54  61  66]
  ...
  [  5  10  22]
  [  7  12  24]
  [  9  14  26]]

 [[ 46  58  67]
  [ 51  63  72]
  [ 57  64  69]
  ...
  [  7  12  22]
  [  9  13  21]
  [  7  11  19]]

 ...

 [[255 255 228]
  [255 255 228]
  [255 255 228]
  ...
  [ 21  24  41]
  [ 21  27  42]
  [ 22  28  43]]

 [[255 255 228]
  [255 255 228]
  [255 255 228]
  ...
  [ 23  26  43]
  [ 23  26  43]
  [ 24  27  44]]

 [[255 255 228]
  [255 255 228]
  [255 255 228]
  ...
  [ 21  27  42]
  [ 23  27  42]
  [ 23  27  42]]]
True
[[[ 24  41  44]
  [ 27  44  47]
  [ 32  49  52]
  ...
  [ 11  26  28]
  [ 19  30  30]
  [ 19  30  30]]

 [[ 23  38  46]
  [ 27  42  50]
  [ 30  49  52]
  ...
  [ 17  24  29]
  [ 16  26  29]
  [ 16  26  29]]

 [[ 19  36  46]
  [ 22  39  49]
  [ 28  45  53]
  ...
  [ 17  25  28]
  [ 18  26  29]
  [ 18  26  29]]

 ...

 [[255 255 224]
  [255 255 224]
  [255 255

True
[[[ 13  19  34]
  [ 13  19  34]
  [ 13  20  32]
  ...
  [  7  11  19]
  [  9  12  22]
  [ 11  14  24]]

 [[  8  23  33]
  [  7  22  32]
  [ 10  16  31]
  ...
  [  3  11  19]
  [ 10  13  23]
  [ 11  14  24]]

 [[ 13  18  35]
  [ 10  15  32]
  [ 10  15  32]
  ...
  [  5  14  19]
  [  6  15  20]
  [  7  16  21]]

 ...

 [[103  85  84]
  [103  85  84]
  [103  85  84]
  ...
  [  7  11  19]
  [  9  12  24]
  [  9  12  24]]

 [[ 97  82  80]
  [100  85  83]
  [103  85  84]
  ...
  [  6   8  14]
  [  7   9  15]
  [  9  11  17]]

 [[ 99  81  80]
  [102  84  83]
  [103  85  84]
  ...
  [  4   8  16]
  [  2   9  14]
  [  5  12  17]]]
True
[[[ 7 18 18]
  [ 8 19 19]
  [ 7 18 18]
  ...
  [ 7 10 22]
  [ 9 12 22]
  [10 13 23]]

 [[ 7 16 21]
  [ 7 16 21]
  [ 7 15 23]
  ...
  [ 7 12 24]
  [ 9 12 24]
  [ 7 10 22]]

 [[ 3 17 21]
  [ 3 17 21]
  [ 3 17 21]
  ...
  [ 5 10 22]
  [ 5  9 17]
  [ 5  9 17]]

 ...

 [[38 35 51]
  [38 35 51]
  [36 34 47]
  ...
  [ 7 12 24]
  [ 7 10 27]
  [ 8 11 28]]

 [[40 34 5

True
[[[ 45  80  90]
  [ 45  80  90]
  [ 53  79  90]
  ...
  [ 19  26  38]
  [ 19  29  38]
  [ 19  29  38]]

 [[ 51  78  91]
  [ 51  78  91]
  [ 55  77  91]
  ...
  [ 14  23  37]
  [ 17  26  40]
  [ 17  26  40]]

 [[ 54  80  91]
  [ 53  79  90]
  [ 59  77  90]
  ...
  [ 14  20  35]
  [ 14  21  33]
  [ 13  20  32]]

 ...

 [[255 255 225]
  [255 255 225]
  [255 255 225]
  ...
  [  8  23  31]
  [ 12  26  30]
  [ 15  29  33]]

 [[255 255 224]
  [255 255 224]
  [255 255 224]
  ...
  [  8  23  31]
  [ 12  27  29]
  [ 12  27  29]]

 [[255 255 224]
  [255 255 224]
  [255 255 226]
  ...
  [  8  23  31]
  [  8  27  30]
  [  8  27  30]]]
True
[[[ 81  82 104]
  [ 81  82 104]
  [ 72  81 100]
  ...
  [ 17  26  40]
  [ 17  29  40]
  [ 12  24  35]]

 [[ 75  83 104]
  [ 73  81 102]
  [ 67  78  98]
  ...
  [ 13  27  40]
  [ 13  27  40]
  [  8  22  35]]

 [[ 75  81 102]
  [ 74  80 101]
  [ 74  80 101]
  ...
  [ 12  21  35]
  [ 11  20  34]
  [  8  17  31]]

 ...

 [[255 255 225]
  [255 255 225]
  [255 255

True
[[[178 193 187]
  [180 195 189]
  [178 194 191]
  ...
  [183 190 188]
  [181 191 186]
  [181 191 186]]

 [[180 195 189]
  [180 195 189]
  [178 195 189]
  ...
  [185 189 188]
  [183 190 188]
  [183 190 188]]

 [[179 195 192]
  [179 195 192]
  [177 196 192]
  ...
  [186 189 185]
  [185 189 188]
  [185 189 188]]

 ...

 [[ 88 116 127]
  [ 87 115 126]
  [ 78 114 121]
  ...
  [192 202 211]
  [198 203 215]
  [199 204 216]]

 [[ 82 113 121]
  [ 82 113 121]
  [ 82 114 118]
  ...
  [192 202 211]
  [198 203 215]
  [198 203 215]]

 [[ 78 114 121]
  [ 78 114 121]
  [ 78 114 121]
  ...
  [190 202 211]
  [194 204 213]
  [194 204 213]]]
True
[[[182 196 194]
  [182 196 194]
  [181 195 194]
  ...
  [189 191 185]
  [190 191 187]
  [190 191 187]]

 [[182 196 194]
  [182 196 194]
  [181 195 193]
  ...
  [189 191 185]
  [189 191 185]
  [189 191 185]]

 [[184 195 193]
  [184 195 193]
  [181 195 193]
  ...
  [187 193 182]
  [187 192 183]
  [186 191 182]]

 ...

 [[ 85 116 124]
  [ 86 117 125]
  [ 90 117